/**
 * Generates supabase/seed_universes.sql from the app's REAL preset definitions
 * (constants/lifelogs.ts + constants/lifelogUniverses.generated.ts) — every
 * preset that carries a `universe`: the 5 originals (grp = 'Popular') and the 77
 * expanded ones (their real group). Writes one idempotent upsert per universe.
 *
 * Run:  npx tsx scripts/generate-universe-seed.ts
 * It ONLY writes the .sql file + prints a summary — it never touches Supabase.
 */
import * as fs from 'fs';
import * as path from 'path';
import { COLLECTION_PRESETS, EXPANDED_PRESETS } from '../constants/lifelogs';
import type { UniverseItem } from '../lib/universes';

type Row = { id: string; name: string; emoji: string; grp: string; items: UniverseItem[] };

const rows: Row[] = [];
// Originals with a universe → grp 'Popular' (exact ids/names/emojis/items).
for (const p of COLLECTION_PRESETS) {
  if (!p.universe) continue;
  rows.push({ id: p.id, name: p.name, emoji: p.emoji, grp: 'Popular', items: p.universe });
}
// Expanded seeded universes → their real group.
for (const p of EXPANDED_PRESETS) {
  if (!p.universe) continue;
  rows.push({ id: p.id, name: p.name, emoji: p.emoji, grp: p.group ?? 'Other', items: p.universe });
}

// ---- sanity ----------------------------------------------------------------
const ids = rows.map(r => r.id);
const dupIds = [...new Set(ids.filter((id, i) => ids.indexOf(id) !== i))];
const totalItems = rows.reduce((s, r) => s + r.items.length, 0);
const countOf = (id: string) => rows.find(r => r.id === id)?.items.length;

// ---- SQL emit --------------------------------------------------------------
// SQL string literal: double single quotes. items go in as a JSON string cast to
// jsonb — JSON.stringify escapes " and \, then we double ' for the '...' literal.
const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;
const jsonbLit = (arr: UniverseItem[]) => `${sqlStr(JSON.stringify(arr))}::jsonb`;

const lines: string[] = [
  '-- Seed data for the `universes` table (id, name, emoji, grp, items, updated_at).',
  '-- AUTO-GENERATED by scripts/generate-universe-seed.ts — do not hand-edit.',
  `-- Regenerate: npx tsx scripts/generate-universe-seed.ts`,
  `-- Universes: ${rows.length} · items: ${totalItems}`,
  '',
];
for (const r of rows) {
  lines.push(
    `INSERT INTO universes (id, name, emoji, grp, items, updated_at) VALUES ` +
    `(${sqlStr(r.id)}, ${sqlStr(r.name)}, ${sqlStr(r.emoji)}, ${sqlStr(r.grp)}, ${jsonbLit(r.items)}, now())`,
  );
  lines.push(
    `ON CONFLICT (id) DO UPDATE SET name=excluded.name, emoji=excluded.emoji, ` +
    `grp=excluded.grp, items=excluded.items, updated_at=now();`,
  );
}
const sql = lines.join('\n') + '\n';

const outPath = path.join(process.cwd(), 'supabase', 'seed_universes.sql');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, sql, 'utf8');

// ---- summary ---------------------------------------------------------------
console.log('── Universe seed generated ─────────────────────────────');
console.log('file:            ', outPath);
console.log('total universes: ', rows.length, '(expect 82)');
console.log('total items:     ', totalItems, '(expect ~4,600)');
console.log('duplicate ids:   ', dupIds.length ? dupIds.join(', ') : 'none');
console.log('spot checks:');
console.log('  countries              =', countOf('countries'), '(expect 195)');
console.log('  national_parks         =', countOf('national_parks'), '(expect 63)');
console.log('  mlb_ballparks          =', countOf('mlb_ballparks'), '(expect 30)');
console.log('  disney_parks           =', countOf('disney_parks'), '(report actual)');
console.log('  one_bite_pizza_top_100 =', countOf('one_bite_pizza_top_100'), '(expect 100)');
